# Branch Policy: Enforce allowed prefixes for branch names
# Allowed prefixes: issue/, fix/

name: 'Branch Name Policy'
on:
  create:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name prefix
        if: github.ref_type == 'branch'
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ ! "$BRANCH_NAME" =~ ^(issue|fix)/ ]]; then
            echo "Branch name '$BRANCH_NAME' does not start with 'issue/' or 'fix/'."
            exit 1
          fi
        shell: bash
