name: Auto-update PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            let summary = `### PR Summary\n`;
            summary += `- **Title:** ${pr.data.title}\n`;
            summary += `- **Author:** @${pr.data.user.login}\n`;
            summary += `- **Commits:** ${commits.data.length}\n`;
            summary += `\n#### Commit Messages\n`;
            for (const c of commits.data) {
              summary += `- ${c.commit.message.split('\n')[0]}\n`;
            }
            return summary;
      - name: Update PR description
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: `${process.env.PR_SUMMARY}\n\n_Auto-generated by workflow_`
            });
        env:
          PR_SUMMARY: ${{ steps.pr.outputs.result }}
