# GitHub Actions Workflow: Deploy Connectivity Landing Zone
# Follows industry best practices for security, compliance, and modularity

name: 'Deploy Connectivity Landing Zone'

on:
  workflow_dispatch:
  push:
    paths:
      - 'landingzones/connectivity/**'
    # Exclude devops-agent subfolder to avoid double deployment
    # Only deploy remaining connectivity resources
    # (devops-agent handled by its own workflow)
    # If your runner supports it, use:
    # paths-ignore:
    #   - 'landingzones/connectivity/devops-agent/**'
      - 'core-modules/**'
      - '.github/workflows/deploy-connectivity.yml'

permissions:
  id-token: write # For OIDC authentication
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5


      - name: Terraform Init (Connectivity)
        run: terraform -chdir=landingzones/connectivity init -backend-config="key=connectivity.terraform.tfstate"

      - name: Terraform Plan (Connectivity)
        run: terraform -chdir=landingzones/connectivity plan -out=connectivity-tfplan

      - name: Terraform Apply (Connectivity)
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=landingzones/connectivity apply -auto-approve connectivity-tfplan

      - name: Post-Apply Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: landingzones/connectivity

      - name: Upload Terraform Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-tfplan
          path: landingzones/connectivity/connectivity-tfplan
