

name: Deploy Azure Policy


on:
  push:
    paths:
      - 'policies/azure/definitions/**'
      - '.github/workflows/deploy-azure-policy.yml'

jobs:
  deploy-policy:
    runs-on: ubuntu-latest
    env:
      MGMT_GROUP: ajch_mgt_grp_01
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}




      - name: Create or Update All Policy Definitions
        run: |
          for file in policies/azure/definitions/*.json; do
            policy_name=$(basename "$file" .json)
            echo "Processing $policy_name"
            az policy definition show --name "$policy_name" --management-group "$MGMT_GROUP"
            if [ $? -ne 0 ]; then
              echo "Creating $policy_name"
              az policy definition create \
                --name "$policy_name" \
                --rules "$file" \
                --mode All \
                --management-group "$MGMT_GROUP"
            else
              echo "Updating $policy_name"
              az policy definition update \
                --name "$policy_name" \
                --rules "$file" \
                --management-group "$MGMT_GROUP"
            fi
          done

      - name: Assign All Policies
        run: |
          for file in policies/azure/definitions/*.json; do
            policy_name=$(basename "$file" .json)
            echo "Assigning $policy_name"
            az policy assignment create \
              --name "assign-$policy_name" \
              --policy "$policy_name" \
              --management-group "$MGMT_GROUP" || echo "Assignment for $policy_name may already exist."
          done


