# GitHub Actions Workflow: Deploy Connectivity Landing Zone
# Follows industry best practices for security, compliance, and modularity

name: 'Deploy Connectivity Landing Zone'

on:
  workflow_dispatch:
  push:
    paths:
      - 'landingzones/connectivity/**'
      - 'core-modules/**'
      - '.github/workflows/deploy-connectivity.yml'

permissions:
  id-token: write # For OIDC authentication
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=landingzones/connectivity init

      - name: Terraform Plan
        run: terraform -chdir=landingzones/connectivity plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=landingzones/connectivity apply -auto-approve tfplan

      - name: Post-Apply Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: landingzones/connectivity

      - name: Upload Terraform Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: landingzones/connectivity/tfplan
