
name: Deploy Azure Policy

on:
  push:
    paths:
      - 'policies/azure/definitions/**'
      - '.github/workflows/deploy-azure-policy.yml'

jobs:
  deploy-policy:
    runs-on: ubuntu-latest
    env:
      AZURE_POLICY_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      MGMT_GROUP: ajch_mgt_grp_01
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (Managed Identity)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_POLICY_CLIENT_ID }}
          enable-federated-credential: true
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Validate All Policy JSON Files
        run: |
          for file in policies/azure/definitions/*.json; do
            echo "Validating $file"
            jq empty "$file"
          done

      - name: Create or Update All Policy Definitions
        run: |
          for file in policies/azure/definitions/*.json; do
            policy_name=$(basename "$file" .json)
            echo "Processing $policy_name"
            az policy definition show --name "$policy_name" --management-group "$MGMT_GROUP"
            if [ $? -ne 0 ]; then
              echo "Creating $policy_name"
              az policy definition create \
                --name "$policy_name" \
                --rules "$file" \
                --mode All \
                --management-group "$MGMT_GROUP"
            else
              echo "Updating $policy_name"
              az policy definition update \
                --name "$policy_name" \
                --rules "$file" \
                --management-group "$MGMT_GROUP"
            fi
          done

      - name: Assign All Policies
        run: |
          for file in policies/azure/definitions/*.json; do
            policy_name=$(basename "$file" .json)
            echo "Assigning $policy_name"
            az policy assignment create \
              --name "assign-$policy_name" \
              --policy "$policy_name" \
              --management-group "$MGMT_GROUP" || echo "Assignment for $policy_name may already exist."
          done


      - name: Run Compliance Scan
        run: |
          az policy state trigger-scan --management-group "$MGMT_GROUP"
          az policy state list --management-group "$MGMT_GROUP"

      - name: Output Success
        run: echo "Azure Policy deployment and compliance scan completed."
